// <auto-generated />
namespace code_first_db_v4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_desc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_desc));
        
        string IMigrationMetadata.Id
        {
            get { return "202404301103263_remove_desc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
